name: Merge Main Tasks
on:
  push:
    branches: main

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Create GitHub release and git tag
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: release
        id: release
        uses: nitrobox/release-on-push-action@v1.0.0
        with:
          tag_prefix: "" # in all places except GitHub we use the version without v
          bump_version_scheme: minor
          use_github_release_notes: true
    outputs:
      fixVersion: ${{ steps.release.outputs.version }}
  
  jira-integration:
    if: needs.release.outputs.fixVersion != ''
    uses: nitrobox/template-actions-main/.github/workflows/jira-integration.yml@v2.11.0
    needs: release
    secrets: inherit
    with:
      service: library-rsql-jpa
      fixVersion: ${{ needs.release.outputs.fixVersion }}









