name: Main Branch Pull Request
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: nitrobox/template-actions-main/.github/workflows/java-quality-checks.yml@v2.14.4
    secrets: inherit
    with:
      java-version: 17
